canal:
  clients:
    simpleInstance:
      enable: true
      mode: simple
      servers: 101.200.230.235:11111
      batchSize: 1000
      destination: example
      getMessageTimeOutMS: 500
    #zkInstance:
    #   enable: true
    #   mode: zookeeper
    #   servers: 172.30.1.6:2181,172.30.1.7:2181,172.30.1.8:2181
    #   batchSize: 1000
    #   #filter: order_center.car_fact_order
    #   destination: example
    #   getMessageTimeOutMS: 500