#项目标准输出配置
system-std:
  open: false
  path: ./log
  retainDays: 5
  rolloverBackupFormat: HHmmssSSS
  rolloverFileFormat: yyyy-MM-dd

canal:
  # 配置说明见: com/bytearch/canal/client/configuration/CanalClientConfig.java
  clients:
    - clientClass: com.bytearch.canal.client.client.CarFactOrderToMQ
      status: enable
      zkServers: dev-zk01-a.zk.01zhuanche.com:2181
      destination: car_fact_order_canal_msg
      filter: order_center.car_fact_order
      getMessageTimeout: 1000
      batchSize: 5120
      retryTimesWhenSendFailed: 6
      namesrvAddr: dev-rq01-a.mq.01zhuanche.com:9876
      topic: car_fact_order_canal_msg