spring:
  # dubbo-service
  application:
    name: dubbo-demo-consumer
dubbo:
  application:
    name: ${spring.application.name}
    owner: bytearch
  registry:
    address: 172.30.1.201:8848
    protocol: nacos
    #parameters:
      # 使用命令空间区分不同环境
     # namespace: 1e4027b5-e09e-407b-a335-8d2374d200ce
  protocol:
    name: dubbo
  scan:
    base-packages: com.bytearch.demo.consumer
  consumer:
    #filter: xxxxMonitorFilter,xxxMonitorFilter
    shareconnections: 10
    lazy: true