spring:
  # dubbo-service
  application:
    name: dubbo-demo-provider
dubbo:
  application:
    name: ${spring.application.name}
    owner: bytearch
    logger: log4j
    shutwait: 15000
  registry:
    address: 172.30.1.201:8848
    protocol: nacos
    #parameters:
      # 使用命令空间区分不同环境
      #namespace: 1e4027b5-e09e-407b-a335-8d2374d200ce
  protocol:
    name: dubbo
    port: 20880
    corethreads: 150
    threads: 800
    threadpool: cached
    dispatcher: message
  scan:
    base-packages: com.bytearch.demo.provider
  provider:
    delay: 15000
    loadbalance: leastactive
    #filter: xxxxFilter,xxxxFilter
